# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\main\python\ui\form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainBaseForm(object):
    def setupUi(self, MainBaseForm):
        MainBaseForm.setObjectName("MainBaseForm")
        MainBaseForm.resize(925, 551)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainBaseForm.sizePolicy().hasHeightForWidth())
        MainBaseForm.setSizePolicy(sizePolicy)

        self.gridLayout.setObjectName("gridLayout")
        self.patient_layout = QtWidgets.QVBoxLayout()
        self.patient_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.patient_layout.setObjectName("patient_layout")
        self.patient_gridLayout = QtWidgets.QGridLayout()
        self.patient_gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.patient_gridLayout.setObjectName("patient_gridLayout")
        self.patient_label = QtWidgets.QLabel(MainBaseForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.patient_label.setFont(font)
        self.patient_label.setAlignment(QtCore.Qt.AlignCenter)
        self.patient_label.setObjectName("patient_label")
        self.patient_gridLayout.addWidget(self.patient_label, 0, 0, 1, 1)
        self.add_patient_btn = QtWidgets.QPushButton(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_patient_btn.sizePolicy().hasHeightForWidth())
        self.add_patient_btn.setSizePolicy(sizePolicy)
        self.add_patient_btn.setObjectName("add_patient_btn")
        self.patient_gridLayout.addWidget(self.add_patient_btn, 2, 0, 1, 1)
        self.del_patient_btn = QtWidgets.QPushButton(MainBaseForm)
        self.del_patient_btn.setObjectName("del_patient_btn")
        self.patient_gridLayout.addWidget(self.del_patient_btn, 3, 0, 1, 1)
        self.patient_list = QtWidgets.QListWidget(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patient_list.sizePolicy().hasHeightForWidth())
        self.patient_list.setSizePolicy(sizePolicy)
        self.patient_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.patient_list.setBatchSize(150)
        self.patient_list.setObjectName("patient_list")
        self.patient_gridLayout.addWidget(self.patient_list, 1, 0, 1, 1)
        self.patient_layout.addLayout(self.patient_gridLayout)
        self.gridLayout.addLayout(self.patient_layout, 0, 3, 1, 1)
        self.data_layout = QtWidgets.QVBoxLayout()
        self.data_layout.setObjectName("data_layout")
        self.report_layout = QtWidgets.QGridLayout()
        self.report_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.report_layout.setObjectName("report_layout")
        self.report_btn = QtWidgets.QPushButton(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.report_btn.sizePolicy().hasHeightForWidth())
        self.report_btn.setSizePolicy(sizePolicy)
        self.report_btn.setObjectName("report_btn")
        self.report_layout.addWidget(self.report_btn, 0, 0, 1, 1)
        self.data_layout.addLayout(self.report_layout)
        self.gridLayout.addLayout(self.data_layout, 0, 4, 1, 1)
        self.group_layout = QtWidgets.QVBoxLayout()
        self.group_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.group_layout.setObjectName("group_layout")
        self.group_gridLayout = QtWidgets.QGridLayout()
        self.group_gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.group_gridLayout.setObjectName("group_gridLayout")
        self.add_group_btn = QtWidgets.QPushButton(MainBaseForm)
        self.add_group_btn.setObjectName("add_group_btn")
        self.group_gridLayout.addWidget(self.add_group_btn, 2, 0, 1, 1)
        self.group_list = QtWidgets.QListWidget(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_list.sizePolicy().hasHeightForWidth())
        self.group_list.setSizePolicy(sizePolicy)
        self.group_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.group_list.setBatchSize(150)
        self.group_list.setObjectName("group_list")
        self.group_gridLayout.addWidget(self.group_list, 1, 0, 1, 1)
        self.del_group_btn = QtWidgets.QPushButton(MainBaseForm)
        self.del_group_btn.setObjectName("del_group_btn")
        self.group_gridLayout.addWidget(self.del_group_btn, 3, 0, 1, 1)
        self.group_label = QtWidgets.QLabel(MainBaseForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.group_label.setFont(font)
        self.group_label.setAlignment(QtCore.Qt.AlignCenter)
        self.group_label.setObjectName("group_label")
        self.group_gridLayout.addWidget(self.group_label, 0, 0, 1, 1)
        self.group_layout.addLayout(self.group_gridLayout)
        self.gridLayout.addLayout(self.group_layout, 0, 1, 1, 1)
        self.ref_layout = QtWidgets.QVBoxLayout()
        self.ref_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ref_layout.setObjectName("ref_layout")
        self.ref_gridLayout = QtWidgets.QGridLayout()
        self.ref_gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ref_gridLayout.setObjectName("ref_gridLayout")
        self.ref_list = QtWidgets.QListWidget(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_list.sizePolicy().hasHeightForWidth())
        self.ref_list.setSizePolicy(sizePolicy)
        self.ref_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ref_list.setBatchSize(150)
        self.ref_list.setObjectName("ref_list")
        self.ref_gridLayout.addWidget(self.ref_list, 1, 0, 1, 1)
        self.add_ref_btn = QtWidgets.QPushButton(MainBaseForm)
        self.add_ref_btn.setObjectName("add_ref_btn")
        self.ref_gridLayout.addWidget(self.add_ref_btn, 2, 0, 1, 1)
        self.del_ref_btn = QtWidgets.QPushButton(MainBaseForm)
        self.del_ref_btn.setObjectName("del_ref_btn")
        self.ref_gridLayout.addWidget(self.del_ref_btn, 3, 0, 1, 1)
        self.ref_label = QtWidgets.QLabel(MainBaseForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ref_label.setFont(font)
        self.ref_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ref_label.setObjectName("ref_label")
        self.ref_gridLayout.addWidget(self.ref_label, 0, 0, 1, 1)
        self.ref_layout.addLayout(self.ref_gridLayout)
        self.gridLayout.addLayout(self.ref_layout, 0, 0, 1, 1)

        self.retranslateUi(MainBaseForm)
        QtCore.QMetaObject.connectSlotsByName(MainBaseForm)

    def retranslateUi(self, MainBaseForm):
        _translate = QtCore.QCoreApplication.translate
        MainBaseForm.setWindowTitle(_translate("MainBaseForm", "Form"))
        self.patient_label.setText(_translate("MainBaseForm", "Пациенты"))
        self.add_patient_btn.setText(_translate("MainBaseForm", "Добавить"))
        self.del_patient_btn.setText(_translate("MainBaseForm", "Удалить"))
        self.report_btn.setText(_translate("MainBaseForm", "Сформировать отчёт"))
        self.add_group_btn.setText(_translate("MainBaseForm", "Добавить группу"))
        self.del_group_btn.setText(_translate("MainBaseForm", "Удалить группу"))
        self.group_label.setText(_translate("MainBaseForm", "Группы"))
        self.add_ref_btn.setText(_translate("MainBaseForm", "Добавить эталон"))
        self.del_ref_btn.setText(_translate("MainBaseForm", "Удалить эталон"))
        self.ref_label.setText(_translate("MainBaseForm", "Эталоны"))

