# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\main\python\ui\form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainBaseForm(object):
    def setupUi(self, MainBaseForm):
        MainBaseForm.setObjectName("MainBaseForm")
        MainBaseForm.resize(847, 446)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainBaseForm.sizePolicy().hasHeightForWidth())
        MainBaseForm.setSizePolicy(sizePolicy)
        MainBaseForm.setMaximumSize(QtCore.QSize(16777215, 16777215))

        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ref_layout = QtWidgets.QGridLayout()
        self.ref_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ref_layout.setHorizontalSpacing(6)
        self.ref_layout.setObjectName("ref_layout")
        self.ref_list = QtWidgets.QListWidget(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_list.sizePolicy().hasHeightForWidth())
        self.ref_list.setSizePolicy(sizePolicy)
        self.ref_list.setMinimumSize(QtCore.QSize(150, 0))
        self.ref_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ref_list.setBatchSize(150)
        self.ref_list.setObjectName("ref_list")
        self.ref_layout.addWidget(self.ref_list, 1, 0, 1, 1)
        self.add_ref_btn = QtWidgets.QPushButton(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_ref_btn.sizePolicy().hasHeightForWidth())
        self.add_ref_btn.setSizePolicy(sizePolicy)
        self.add_ref_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.add_ref_btn.setObjectName("add_ref_btn")
        self.ref_layout.addWidget(self.add_ref_btn, 2, 0, 1, 1)
        self.del_ref_btn = QtWidgets.QPushButton(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_ref_btn.sizePolicy().hasHeightForWidth())
        self.del_ref_btn.setSizePolicy(sizePolicy)
        self.del_ref_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.del_ref_btn.setObjectName("del_ref_btn")
        self.ref_layout.addWidget(self.del_ref_btn, 3, 0, 1, 1)
        self.ref_label = QtWidgets.QLabel(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_label.sizePolicy().hasHeightForWidth())
        self.ref_label.setSizePolicy(sizePolicy)
        self.ref_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ref_label.setFont(font)
        self.ref_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ref_label.setObjectName("ref_label")
        self.ref_layout.addWidget(self.ref_label, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.ref_layout)
        self.pat_layout = QtWidgets.QGridLayout()
        self.pat_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.pat_layout.setObjectName("pat_layout")
        self.del_pat_btn = QtWidgets.QPushButton(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_pat_btn.sizePolicy().hasHeightForWidth())
        self.del_pat_btn.setSizePolicy(sizePolicy)
        self.del_pat_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.del_pat_btn.setObjectName("del_pat_btn")
        self.pat_layout.addWidget(self.del_pat_btn, 4, 0, 1, 1)
        self.add_pat_btn = QtWidgets.QPushButton(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_pat_btn.sizePolicy().hasHeightForWidth())
        self.add_pat_btn.setSizePolicy(sizePolicy)
        self.add_pat_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.add_pat_btn.setObjectName("add_pat_btn")
        self.pat_layout.addWidget(self.add_pat_btn, 3, 0, 1, 1)
        self.pat_list = QtWidgets.QListWidget(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pat_list.sizePolicy().hasHeightForWidth())
        self.pat_list.setSizePolicy(sizePolicy)
        self.pat_list.setMinimumSize(QtCore.QSize(150, 0))
        self.pat_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pat_list.setBatchSize(150)
        self.pat_list.setObjectName("pat_list")
        self.pat_layout.addWidget(self.pat_list, 2, 0, 1, 1)
        self.pat_label = QtWidgets.QLabel(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pat_label.sizePolicy().hasHeightForWidth())
        self.pat_label.setSizePolicy(sizePolicy)
        self.pat_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pat_label.setFont(font)
        self.pat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pat_label.setObjectName("pat_label")
        self.pat_layout.addWidget(self.pat_label, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.pat_layout)
        self.data_layout = QtWidgets.QVBoxLayout()
        self.data_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.data_layout.setContentsMargins(0, -1, -1, -1)
        self.data_layout.setObjectName("data_layout")
        self.report_btn = QtWidgets.QPushButton(MainBaseForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.report_btn.sizePolicy().hasHeightForWidth())
        self.report_btn.setSizePolicy(sizePolicy)
        self.report_btn.setObjectName("report_btn")
        self.data_layout.addWidget(self.report_btn)
        self.horizontalLayout.addLayout(self.data_layout)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(MainBaseForm)
        QtCore.QMetaObject.connectSlotsByName(MainBaseForm)

    def retranslateUi(self, MainBaseForm):
        _translate = QtCore.QCoreApplication.translate
        MainBaseForm.setWindowTitle(_translate("MainBaseForm", "Form"))
        self.add_ref_btn.setText(_translate("MainBaseForm", "Добавить"))
        self.del_ref_btn.setText(_translate("MainBaseForm", "Удалить"))
        self.ref_label.setText(_translate("MainBaseForm", "Эталоны"))
        self.del_pat_btn.setText(_translate("MainBaseForm", "Удалить"))
        self.add_pat_btn.setText(_translate("MainBaseForm", "Добавить"))
        self.pat_label.setText(_translate("MainBaseForm", "Пациенты"))
        self.report_btn.setText(_translate("MainBaseForm", "Сформировать отчёт"))

