# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\main\python\ui\health_weather.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainBaseForm(object):
    def setupUi(self, MainBaseForm):
        MainBaseForm.setObjectName("MainBaseForm")
        MainBaseForm.resize(1232, 632)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(MainBaseForm)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(480, 0, 751, 631))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.data_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.data_layout.setContentsMargins(0, 0, 0, 0)
        self.data_layout.setObjectName("data_layout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.kde_tab = QtWidgets.QWidget()
        self.kde_tab.setObjectName("kde_tab")
        self.tabWidget.addTab(self.kde_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.data_layout.addWidget(self.tabWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.exit_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.exit_btn.setObjectName("exit_btn")
        self.gridLayout.addWidget(self.exit_btn, 0, 1, 1, 1)
        self.report_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.report_btn.setObjectName("report_btn")
        self.gridLayout.addWidget(self.report_btn, 0, 0, 1, 1)
        self.data_layout.addLayout(self.gridLayout)
        self.verticalLayoutWidget = QtWidgets.QWidget(MainBaseForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 160, 631))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ref_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ref_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ref_layout.setContentsMargins(0, 0, 0, 0)
        self.ref_layout.setObjectName("ref_layout")
        self.ref_gridLayout = QtWidgets.QGridLayout()
        self.ref_gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ref_gridLayout.setObjectName("ref_gridLayout")
        self.ref_list = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.ref_list.setObjectName("ref_list")
        self.ref_gridLayout.addWidget(self.ref_list, 1, 0, 1, 1)
        self.add_ref_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add_ref_btn.setObjectName("add_ref_btn")
        self.ref_gridLayout.addWidget(self.add_ref_btn, 2, 0, 1, 1)
        self.del_ref_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.del_ref_btn.setObjectName("del_ref_btn")
        self.ref_gridLayout.addWidget(self.del_ref_btn, 3, 0, 1, 1)
        self.ref_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ref_label.setFont(font)
        self.ref_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ref_label.setObjectName("ref_label")
        self.ref_gridLayout.addWidget(self.ref_label, 0, 0, 1, 1)
        self.ref_layout.addLayout(self.ref_gridLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(MainBaseForm)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 0, 160, 631))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.group_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.group_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.group_layout.setContentsMargins(0, 0, 0, 0)
        self.group_layout.setObjectName("group_layout")
        self.group_gridLayout = QtWidgets.QGridLayout()
        self.group_gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.group_gridLayout.setObjectName("group_gridLayout")
        self.group_list = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.group_list.setObjectName("group_list")
        self.group_gridLayout.addWidget(self.group_list, 1, 0, 1, 1)
        self.add_group_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.add_group_btn.setObjectName("add_group_btn")
        self.group_gridLayout.addWidget(self.add_group_btn, 2, 0, 1, 1)
        self.del_group_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.del_group_btn.setObjectName("del_group_btn")
        self.group_gridLayout.addWidget(self.del_group_btn, 3, 0, 1, 1)
        self.group_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.group_label.setFont(font)
        self.group_label.setAlignment(QtCore.Qt.AlignCenter)
        self.group_label.setObjectName("group_label")
        self.group_gridLayout.addWidget(self.group_label, 0, 0, 1, 1)
        self.group_layout.addLayout(self.group_gridLayout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(MainBaseForm)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(320, 0, 160, 631))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.patient_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.patient_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.patient_layout.setContentsMargins(0, 0, 0, 0)
        self.patient_layout.setObjectName("patient_layout")
        self.patient_gridLayout = QtWidgets.QGridLayout()
        self.patient_gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.patient_gridLayout.setObjectName("patient_gridLayout")
        self.patient_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.patient_label.setFont(font)
        self.patient_label.setAlignment(QtCore.Qt.AlignCenter)
        self.patient_label.setObjectName("patient_label")
        self.patient_gridLayout.addWidget(self.patient_label, 0, 0, 1, 1)
        self.add_patient_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.add_patient_btn.setObjectName("add_patient_btn")
        self.patient_gridLayout.addWidget(self.add_patient_btn, 2, 0, 1, 1)
        self.patient_list = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.patient_list.setObjectName("patient_list")
        self.patient_gridLayout.addWidget(self.patient_list, 1, 0, 1, 1)
        self.del_patient_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.del_patient_btn.setObjectName("del_patient_btn")
        self.patient_gridLayout.addWidget(self.del_patient_btn, 3, 0, 1, 1)
        self.patient_layout.addLayout(self.patient_gridLayout)

        self.retranslateUi(MainBaseForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainBaseForm)

    def retranslateUi(self, MainBaseForm):
        _translate = QtCore.QCoreApplication.translate
        MainBaseForm.setWindowTitle(_translate("MainBaseForm", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kde_tab), _translate("MainBaseForm", "Совместный KDE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainBaseForm", "Tab 2"))
        self.exit_btn.setText(_translate("MainBaseForm", "Выход"))
        self.report_btn.setText(_translate("MainBaseForm", "Сформировать отчёт"))
        self.add_ref_btn.setText(_translate("MainBaseForm", "Добавить эталон"))
        self.del_ref_btn.setText(_translate("MainBaseForm", "Удалить эталон"))
        self.ref_label.setText(_translate("MainBaseForm", "Эталоны"))
        self.add_group_btn.setText(_translate("MainBaseForm", "Добавить группу"))
        self.del_group_btn.setText(_translate("MainBaseForm", "Удалить группу"))
        self.group_label.setText(_translate("MainBaseForm", "Группы"))
        self.patient_label.setText(_translate("MainBaseForm", "Пациенты"))
        self.add_patient_btn.setText(_translate("MainBaseForm", "Добавить пациента"))
        self.del_patient_btn.setText(_translate("MainBaseForm", "Удалить пациента"))

