# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main/python/ui/frame_sample.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FramePatient(object):
    def setupUi(self, FramePatient):
        FramePatient.setObjectName("FramePatient")
        FramePatient.resize(620, 579)
        FramePatient.setMinimumSize(QtCore.QSize(620, 380))
        self.verticalLayout = QtWidgets.QVBoxLayout(FramePatient)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(FramePatient)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.tabs = QtWidgets.QTabWidget(FramePatient)
        self.tabs.setObjectName("tabs")
        self.tab_factors = QtWidgets.QWidget()
        self.tab_factors.setObjectName("tab_factors")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_factors)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 576, 486))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_kde = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_kde.sizePolicy().hasHeightForWidth())
        self.label_kde.setSizePolicy(sizePolicy)
        self.label_kde.setObjectName("label_kde")
        self.verticalLayout_3.addWidget(self.label_kde)
        self.label_kde3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_kde3.sizePolicy().hasHeightForWidth())
        self.label_kde3.setSizePolicy(sizePolicy)
        self.label_kde3.setObjectName("label_kde3")
        self.verticalLayout_3.addWidget(self.label_kde3)
        self.text_main_1 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_main_1.sizePolicy().hasHeightForWidth())
        self.text_main_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_main_1.setFont(font)
        self.text_main_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.text_main_1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.text_main_1.setDocumentTitle("")
        self.text_main_1.setReadOnly(True)
        self.text_main_1.setObjectName("text_main_1")
        self.verticalLayout_3.addWidget(self.text_main_1)
        self.text_main_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_main_2.setFont(font)
        self.text_main_2.setReadOnly(True)
        self.text_main_2.setObjectName("text_main_2")
        self.verticalLayout_3.addWidget(self.text_main_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabs.addTab(self.tab_factors, "")
        self.tab_factor_0 = QtWidgets.QWidget()
        self.tab_factor_0.setObjectName("tab_factor_0")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_factor_0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabs.addTab(self.tab_factor_0, "")
        self.tab_factor_1 = QtWidgets.QWidget()
        self.tab_factor_1.setObjectName("tab_factor_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_factor_1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabs.addTab(self.tab_factor_1, "")
        self.tab_factor_2 = QtWidgets.QWidget()
        self.tab_factor_2.setObjectName("tab_factor_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_factor_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabs.addTab(self.tab_factor_2, "")
        self.tab_factor_3 = QtWidgets.QWidget()
        self.tab_factor_3.setObjectName("tab_factor_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_factor_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabs.addTab(self.tab_factor_3, "")
        self.verticalLayout.addWidget(self.tabs)

        self.retranslateUi(FramePatient)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FramePatient)

    def retranslateUi(self, FramePatient):
        _translate = QtCore.QCoreApplication.translate
        FramePatient.setWindowTitle(_translate("FramePatient", "Frame"))
        self.title_label.setText(_translate("FramePatient", "Статистика"))
        self.label_kde.setText(_translate("FramePatient", "label_kde"))
        self.label_kde3.setText(_translate("FramePatient", "label_kde3"))
        self.text_main_1.setPlaceholderText(_translate("FramePatient", "Lol kek cheburek"))
        self.text_main_2.setPlaceholderText(_translate("FramePatient", "Lol kek cheburek"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_factors), _translate("FramePatient", "Все факторы"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_factor_0), _translate("FramePatient", "Без нагрузки"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_factor_1), _translate("FramePatient", "После физической"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_factor_2), _translate("FramePatient", "После эмоциональной"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_factor_3), _translate("FramePatient", "После отдыха"))

